//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace debt_fe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentISN { get; set; }
        public Nullable<int> MemberISN { get; set; }
        public string docFileName { get; set; }
        public Nullable<System.DateTime> docAddedDate { get; set; }
        public Nullable<int> docSize { get; set; }
        public Nullable<byte> docPublic { get; set; }
        public Nullable<byte> docStatus { get; set; }
        public string docDesc { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<int> CampaignISN { get; set; }
        public Nullable<int> docAddedBy { get; set; }
        public string docName { get; set; }
        public Nullable<int> docSignatureStatus { get; set; }
        public string docLastAction { get; set; }
        public Nullable<int> CreditorISN { get; set; }
        public Nullable<System.DateTime> docSignatureDate { get; set; }
        public Nullable<int> TemplateISN { get; set; }
        public Nullable<int> CSScheduleISN { get; set; }
        public string docSendIP { get; set; }
        public string docSignatureIP { get; set; }
        public string docGuid { get; set; }
        public Nullable<int> docNoOfSign { get; set; }
        public string docHistory { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
