//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace debt_fe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Documents = new HashSet<Document>();
            this.PremierMessages = new HashSet<PremierMessage>();
        }
    
        public int MemberISN { get; set; }
        public string memUserName { get; set; }
        public string memPassword { get; set; }
        public string memFirstName { get; set; }
        public string memMiddleName { get; set; }
        public string memLastName { get; set; }
        public string memSSN { get; set; }
        public string memEmail { get; set; }
        public string memAddress { get; set; }
        public string memCity { get; set; }
        public string memState { get; set; }
        public string memZip { get; set; }
        public string memCountry { get; set; }
        public string memPhone { get; set; }
        public string memFax { get; set; }
        public byte memStatus { get; set; }
        public Nullable<System.DateTime> memSignUp { get; set; }
        public Nullable<short> memTimeOption { get; set; }
        public Nullable<byte> memDayLightSaving { get; set; }
        public Nullable<System.DateTime> memPinCreateDate { get; set; }
        public Nullable<int> memPinDisableBy { get; set; }
        public Nullable<int> BatchISN { get; set; }
        public Nullable<int> PromotionISN { get; set; }
        public Nullable<int> AgentISN { get; set; }
        public byte memAutoRecharge { get; set; }
        public Nullable<decimal> memLowerThan { get; set; }
        public Nullable<decimal> memWithAmount { get; set; }
        public Nullable<int> PaymentProfileISN { get; set; }
        public string memHomePhone { get; set; }
        public string memMobilePhone { get; set; }
        public string memWorkPhone { get; set; }
        public Nullable<decimal> memCreditLine { get; set; }
        public string memDomainName { get; set; }
        public Nullable<byte> memRechargeBlock { get; set; }
        public Nullable<byte> memInvoice { get; set; }
        public double memAllPinUsage { get; set; }
        public double memCurrPinUsage { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> memAgentDate { get; set; }
        public Nullable<System.DateTime> memDOB { get; set; }
        public Nullable<int> memAddedBy { get; set; }
        public Nullable<byte> memGender { get; set; }
        public string memAccountName { get; set; }
        public string memAccountComment { get; set; }
        public Nullable<int> BankISN { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<PremierMessage> PremierMessages { get; set; }
    }
}
