//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace debt_fe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberExt2
    {
        public MemberExt2()
        {
            this.DebtTemplates = new HashSet<DebtTemplate>();
        }
    
        public int MemberISN { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
        public Nullable<int> DealerISN { get; set; }
        public string PageName { get; set; }
        public Nullable<int> LeadDefaultCampISN { get; set; }
        public Nullable<int> CDRDefaultCampISN { get; set; }
        public Nullable<int> AgencyISN { get; set; }
        public Nullable<int> SalesManagerISN { get; set; }
        public string UniversalUserName { get; set; }
        public string UniversalPassword { get; set; }
        public string MasterMFACode { get; set; }
        public string EPPSUserName { get; set; }
        public string EPPSPassword { get; set; }
    
        public virtual ICollection<DebtTemplate> DebtTemplates { get; set; }
    }
}
